services: docker
env:
- distro: ubuntu1604
- distro: debian8
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: MTFnYR/WwIAVPV4etlOw7aBRqFx6i7waBe5yxeCJy3IXvou2W+wto2GoLaVzEs6ZtTHgsnUo2z1qNWt/3dBbBDSPmYzpwdxwKY9oy+rvrde8W03lgpWDU1jgILWX4C1jzo+1hxKSbaolxXSWkfZ8DDe2QT/vj+y8wmTmwx8KWMfKk7nKwIC7WctfRs+G+hQ0NOfgSArEaCF1NDv5XPJQgMIjCSmHRURhy8vC52kzFzE5d8TspGB0atoLhZkKZnhGxMXzEmuXLXjK0ldPVzcdKrfQYMR/bRdMLc/wbcg/ukFaNrNhvu4XQoSverYJHPUuQEzzRQ/uwLPrLMQQdmbSyhPgxhGkWs5BhHCtrxx7ekxis0nl5dxNRFQMkNmOZCJTBv0hEcIViL30fxSDlefqjX6b/4LRsCmkdHBYFH/Smycw2dvJ8lHzSbDwajrFrwHaCsEkx97QCIbHU5MCnb4qZIDl4oEkL4DOsNPyqBO2kiPCA3i3AQC9bS0BigcVGVcPnPSefNmmj4Tsmdqi/k6o+vrVfUK2Jda5uWHlC+XnWRgydeXa2p/Zk4UuODM2RR/okrDILN0xH4zkJVVDkRyjC4dVcdB3yrs1U/nwbOBeVvsV38WYg9TnzC1/n0ge+73yStcxcXt7VZtQzN4RnWrRGp1XFQu8LDCI2ESycmEc2gM=
