services: docker
env:
- distro: ubuntu1604
- distro: debian8
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: nkiwuUPWQ/MlUikvp2fc1iW6YS/MlP/TwxEbCVHz530cX8Wu7o/Rthw5sCea29yrp4XfA8Qwzyz7NZr5iWd9fT9Z57vp/vqD/CxUh/ISo9H4gheF5HVhR/K5X+xqJMhZPiAQiaqYIftKcFWZlym7w8qTw1rFscAF6mFuqDiRbSyJoShYF2Q4APpykb+yqAAfbkpSrWldH+fCuNUwexRFm0wkfOSNvczvvAHNks7lWVu7O//9uwU/X8tVJwCC7s2rjCR2pbsO1zm/4rEh0D0UsWuQsgVS4J5xL/Z05l0GDPw8gNJrdPuWAJb5qAs64bvBLAW33f0sexkYb7TDZLWzWcETKu3mpCRGCmly7pqiAQQPsMSqlpPUKEcTtnkA+GSlpnIAP5UyAzeQ2GQMz02WCMmmHg8GOzH5o35Wsv7XaH1PFgv1NKhgbiLVRZxnwe+ijPo3wJium1RoijhWYqmvnNckr/c1puiYM5hzyzpk/KOJ2rWRKZtqy+HfkxWA1Cr65A39GpfFETekmW6G/OzvIoTitHQUN7H4OyXh/6t+HXpKxQcZdEDmQ/4JWnUsul6UFiI+0iJN5dCTGPDU1SPqf+KD2tyaRgPNz5RB5U1Ec8LL2LCCREouv/iPI3ZzMQ1xLg4hLYUX0BaECQ8/ZNNmMlusCqK0EOXQ2qBTP3qrSmw=
