- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: ensure sefacl and facl binaries are installed (Debian)
  package:
    name: acl
    state: present

- name: Ensure documentroots exist and have correct access-rights
  become: true
  file:
    path: "{{ item.documentroot }}"
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ lookup('pipe', 'whoami') }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
    recurse: true
  with_items: "{{ apache_vhosts }}"
  register: doc_root_state
  when: apache_vhosts | length > 0
  
- name: Set documentroots current ACLs
  become: true
  shell: "setfacl -R -m u:{{ php_fpm_pool_user }}:rwX -m u:{{ lookup('pipe', 'whoami') }}:rwX {{ item.documentroot }}"
  with_items: "{{ apache_vhosts }}"
  when:
    - doc_root_state.changed

- name: Set documentroots default ACLs
  become: true
  shell: "setfacl -dR -m u:{{ php_fpm_pool_user }}:rwX -m u:{{ lookup('pipe', 'whoami') }}:rwX {{ item.documentroot }}"
  with_items: "{{ apache_vhosts }}"
  when:
    - doc_root_state.changed